// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using devdev_api.Data;

#nullable disable

namespace devdev_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260313193926_UseIdentityByDefaultColumn")]
    partial class UseIdentityByDefaultColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("devdev_api.Domain.Entities.Masters.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<long>("YearId")
                        .HasColumnType("bigint")
                        .HasColumnName("year_id");

                    b.HasKey("Id")
                        .HasName("pk_master_companies");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_master_companies_code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_master_companies_is_active");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_master_companies_is_deleted");

                    b.HasIndex("YearId")
                        .HasDatabaseName("ix_master_companies_year_id");

                    b.ToTable("master_companies", (string)null);
                });

            modelBuilder.Entity("devdev_api.Domain.Entities.Masters.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<long>("FunctionalId")
                        .HasColumnType("bigint")
                        .HasColumnName("functional_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_master_departments");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_master_departments_code");

                    b.HasIndex("FunctionalId")
                        .HasDatabaseName("ix_master_departments_functional_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_master_departments_is_active");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_master_departments_is_deleted");

                    b.ToTable("master_departments", (string)null);
                });

            modelBuilder.Entity("devdev_api.Domain.Entities.Masters.Functional", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_master_functionals");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_master_functionals_code");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_master_functionals_company_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_master_functionals_is_active");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_master_functionals_is_deleted");

                    b.ToTable("master_functionals", (string)null);
                });

            modelBuilder.Entity("devdev_api.Domain.Entities.Masters.Year", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_current");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("YearValue")
                        .HasColumnType("integer")
                        .HasColumnName("year_value");

                    b.HasKey("Id")
                        .HasName("pk_master_years");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_master_years_is_active");

                    b.HasIndex("IsCurrent")
                        .HasDatabaseName("ix_master_years_is_current");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_master_years_is_deleted");

                    b.HasIndex("YearValue")
                        .IsUnique()
                        .HasDatabaseName("ix_master_years_year_value");

                    b.ToTable("master_years", (string)null);
                });

            modelBuilder.Entity("devdev_api.Domain.Entities.RiskProfiles.RiskProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_no");

                    b.Property<int>("DocumentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("document_status_id");

                    b.Property<int?>("FunctionalId")
                        .HasColumnType("integer")
                        .HasColumnName("functional_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_risk_profiles");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_risk_profiles_company_id");

                    b.HasIndex("DocumentNo")
                        .IsUnique()
                        .HasDatabaseName("ix_risk_profiles_document_no")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("DocumentStatusId")
                        .HasDatabaseName("ix_risk_profiles_document_status_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_risk_profiles_is_active");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_risk_profiles_is_deleted");

                    b.HasIndex("CompanyId", "DocumentStatusId", "IsDeleted")
                        .HasDatabaseName("ix_risk_profiles_company_id_document_status_id_is_deleted");

                    b.ToTable("risk_profiles", (string)null);
                });

            modelBuilder.Entity("devdev_api.Domain.Entities.Masters.Company", b =>
                {
                    b.HasOne("devdev_api.Domain.Entities.Masters.Year", "Year")
                        .WithMany("Companies")
                        .HasForeignKey("YearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_master_companies_years_year_id");

                    b.Navigation("Year");
                });

            modelBuilder.Entity("devdev_api.Domain.Entities.Masters.Department", b =>
                {
                    b.HasOne("devdev_api.Domain.Entities.Masters.Functional", "Functional")
                        .WithMany("Departments")
                        .HasForeignKey("FunctionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_master_departments_functionals_functional_id");

                    b.Navigation("Functional");
                });

            modelBuilder.Entity("devdev_api.Domain.Entities.Masters.Functional", b =>
                {
                    b.HasOne("devdev_api.Domain.Entities.Masters.Company", "Company")
                        .WithMany("Functionals")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_master_functionals_master_companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("devdev_api.Domain.Entities.Masters.Company", b =>
                {
                    b.Navigation("Functionals");
                });

            modelBuilder.Entity("devdev_api.Domain.Entities.Masters.Functional", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("devdev_api.Domain.Entities.Masters.Year", b =>
                {
                    b.Navigation("Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
