// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using devdev_api.Data;

#nullable disable

namespace devdev_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260313031323_init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("devdev_api.Domain.Entities.RiskProfiles.RiskProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_no");

                    b.Property<int>("DocumentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("document_status_id");

                    b.Property<int?>("FunctionalId")
                        .HasColumnType("integer")
                        .HasColumnName("functional_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_risk_profiles");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_risk_profiles_company_id");

                    b.HasIndex("DocumentNo")
                        .IsUnique()
                        .HasDatabaseName("ix_risk_profiles_document_no")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("DocumentStatusId")
                        .HasDatabaseName("ix_risk_profiles_document_status_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_risk_profiles_is_active");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_risk_profiles_is_deleted");

                    b.HasIndex("CompanyId", "DocumentStatusId", "IsDeleted")
                        .HasDatabaseName("ix_risk_profiles_company_id_document_status_id_is_deleted");

                    b.ToTable("risk_profiles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
